# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "mr_tween-0.0.0-WbH78YcBAQAyLKpoJZkX_X4gs_gKE5Ac9YqmHupIGjJb";
    path = fetchgit {
      url = "https://codeberg.org/Games-by-Mason/mr_tween.git";
      rev = "fc203039ef3cf130983246a526eb56fb6b110ef0";
      hash = "sha256-HK8GemtYq/pp9Bw3WU6vomOQle8HCr0thtRBady1aw8=";
    };
  }
  {
    name = "wayland-0.5.0-lQa1knz8AQCh08NA8BeQrwJB9U3CfqcVAdHZYGRKIGuu";
    path = fetchgit {
      url = "https://codeberg.org/ifreund/zig-wayland";
      rev = "0b7fc007d6f402496e3ad2d6a7cc9118a2080aa9";
      hash = "sha256-mhqOtC26iACIvQUq74AbLSXSPsnWMi3AvDV7G2uElpo=";
    };
  }
]
